name: Auto Proxy Check

on:
  schedule:
    - cron: "0 */6 * * *"  # Setiap 6 jam
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  check-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Collect & Check Proxies
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
          API_URL: ${{ secrets.API_URL }}
        run: python proxy_checker.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add alive.txt dead.txt
          git commit -m "Update proxy check results" || echo "No changes to commit"
          git push
