name: Proxy Checker

on:
  schedule:
    - cron: "0 */6 * * *"  # Jalankan setiap 6 jam
  workflow_dispatch:

jobs:
  check-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Collect proxies
        env:
          PROXY_SOURCES: ${{ secrets.PROXY_SOURCES }}
        run: python collect_proxies.py >/dev/null 2>&1

      - name: Check proxies
        env:
          API_URL: ${{ secrets.API_URL }}
        run: python proxy_checker.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add alive.txt dead.txt
          git commit -m "Update proxy check results" || exit 0
          git push
